title: Plus Size Master List
description: Plus Size Fashion Links
remote_theme: just-the-docs/just-the-docs
search_enabled: true
url: https://methodphoto.github.io/plus-size-list/
email: richard@method.co.uk
baseurl: "/" # the subpath of your site, e.g. /blog
heading_anchors: false
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

